defmodule Custode.NotebookTest do
  use ExUnit.Case, async: false

  import Custode.TestHelpers

  alias Custode.Memory
  alias Custode.Notebook

  setup do
    workspace = tmp_workspace!()
    routine = routine_fixture!(workspace)
    %{workspace: workspace, routine: routine}
  end

  describe "journal and todos" do
    test "mutations persist, render the markdown views, and broadcast",
         %{workspace: workspace, routine: routine} do
      :ok = Custode.PubSubBridge.subscribe()

      {:ok, entry} =
        Notebook.journal_append(routine.id, "platform sync notes", title: "platform sync")

      {:ok, todo} = Notebook.todo_add(routine.id, "write the README")

      assert_receive {:notebook_changed, _id}

      assert [%{id: entry_id}] = Notebook.journal(routine.id)
      assert entry_id == entry.id

      journal_md = File.read!(Path.join(workspace, "journal.md"))
      assert journal_md =~ "generated by custode"
      assert journal_md =~ "platform sync"

      todo_md = File.read!(Path.join(workspace, "TODO.md"))
      assert todo_md =~ "- [ ] (##{todo.id}) write the README"

      {:ok, _done} = Notebook.todo_complete(todo.id)
      assert Notebook.todos(routine.id, "open") == []
      assert File.read!(Path.join(workspace, "TODO.md")) =~ "- [x] (##{todo.id})"
    end

    test "todo_complete on a missing id" do
      assert {:error, :not_found} = Notebook.todo_complete(999_999)
    end

    test "journaling for an unconfigured routine skips the render, keeps the row" do
      id = uid("sub-agent")
      {:ok, _entry} = Notebook.journal_append(id, "learned a thing")
      assert [%{body: "learned a thing"}] = Notebook.journal(id)
    end

    test "compaction distills live entries into a summary and shrinks the agent's view (#214)",
         %{routine: routine, workspace: workspace} do
      {:ok, _} = Notebook.journal_append(routine.id, "swept on monday")
      {:ok, _} = Notebook.journal_append(routine.id, "swept on tuesday")

      {:ok, %{summarized: 2}} =
        Notebook.compact_journal(routine.id, "two quiet sweeps, nothing changed")

      # the dashboard view keeps the whole trail (3: two originals + summary)
      all = Notebook.journal(routine.id, 50)
      assert length(all) == 3
      assert Enum.any?(all, &(&1.body =~ "two quiet sweeps"))

      # the AGENT's view (live only) is just the summary -- the originals
      # were folded in, so it will not re-distill them
      live = Notebook.journal(routine.id, 50, live_only: true)
      assert [%{source: "compaction", body: "two quiet sweeps, nothing changed"}] = live

      # journal.md re-rendered to the shrunken view
      assert File.read!(Path.join(workspace, "journal.md")) =~ "two quiet sweeps"
      refute File.read!(Path.join(workspace, "journal.md")) =~ "swept on monday"

      # a later entry is live again; a second compaction folds it plus the
      # prior summary
      {:ok, _} = Notebook.journal_append(routine.id, "swept on wednesday")
      {:ok, %{summarized: 2}} = Notebook.compact_journal(routine.id, "still quiet")
      assert [%{body: "still quiet"}] = Notebook.journal(routine.id, 50, live_only: true)
    end
  end

  describe "inbox bookkeeping" do
    test "unfiled_notes lists only unfiled; mark_filed! is idempotent and path-safe",
         %{workspace: workspace, routine: routine} do
      inbox = Path.join(workspace, "inbox")
      File.write!(Path.join(inbox, "a.md"), "note a\n")
      File.write!(Path.join(inbox, "b.md"), "FILED 2026-07-19\n\nnote b\n")

      assert [%{name: "a.md", content: "note a\n"}] = Notebook.unfiled_notes(routine)

      :ok = Notebook.mark_filed!(routine, "a.md")
      :ok = Notebook.mark_filed!(routine, "a.md")

      content = File.read!(Path.join(inbox, "a.md"))
      assert String.starts_with?(content, "FILED ")
      refute content =~ "FILED #{Date.utc_today()}\n\nFILED"
      assert Notebook.unfiled_notes(routine) == []

      assert_raise ArgumentError, fn -> Notebook.mark_filed!(routine, "../journal.md") end
    end
  end

  describe "memory" do
    test "remember upserts by key; recall one or all; forget is idempotent" do
      id = uid("mem")

      :ok = Memory.remember(id, "operator-pref", "keep summaries short")
      :ok = Memory.remember(id, "watching", "the flaky deploy")
      :ok = Memory.remember(id, "operator-pref", "keep summaries VERY short")

      assert {:ok, "keep summaries VERY short"} = Memory.recall(id, "operator-pref")
      assert [%{key: "operator-pref"}, %{key: "watching"}] = Memory.recall(id)
      assert :error = Memory.recall(id, "nope")

      :ok = Memory.forget(id, "watching")
      :ok = Memory.forget(id, "watching")
      assert [%{key: "operator-pref"}] = Memory.recall(id)

      # scoped per agent
      assert Memory.recall(uid("other")) == []
    end
  end
end
