defmodule Custode.MCP.Server do
  @moduledoc "Static native Snodo tool catalog for the custode endpoint."
  @tools [
    Custode.MCP.Tools.ListRoutines,
    Custode.MCP.Tools.AgentStatus,
    Custode.MCP.Tools.StartAgent,
    Custode.MCP.Tools.PromptAgent,
    Custode.MCP.Tools.AwaitAgent,
    Custode.MCP.Tools.AgentHistory,
    Custode.MCP.Tools.ApproveAction,
    Custode.MCP.Tools.RejectAction,
    Custode.MCP.Tools.RunJob,
    Custode.MCP.RosterTools.PreviewRoutine,
    Custode.MCP.RosterTools.AddRoutine,
    Custode.MCP.RosterTools.PreviewRoutineEdit,
    Custode.MCP.RosterTools.UpdateRoutine,
    Custode.MCP.RosterTools.RemoveRoutine,
    Custode.MCP.ProfileTools.PreviewProfile,
    Custode.MCP.ProfileTools.DefineProfile,
    Custode.MCP.ProfileTools.PreviewProfileEdit,
    Custode.MCP.ProfileTools.UpdateProfile,
    Custode.MCP.ProfileTools.RemoveProfile,
    Custode.MCP.Tools.Drain,
    Custode.MCP.RepoTools.OpenPr,
    Custode.MCP.RepoTools.OpenIssue,
    Custode.MCP.RepoTools.Comment,
    Custode.MCP.RepoTools.DraftIssues,
    Custode.MCP.RepoTools.FileDrafts,
    Custode.MCP.RepoTools.ReadyPr,
    Custode.MCP.RepoTools.MergePr,
    Custode.MCP.RepoTools.MarkIssueReady,
    Custode.MCP.RepoTools.MarkIssueBlocked,
    Custode.MCP.RepoTools.ReviewPr,
    Custode.MCP.RepoTools.ListIssues,
    Custode.MCP.RepoTools.ViewIssue,
    Custode.MCP.RepoTools.ListPrs,
    Custode.MCP.RepoTools.ViewPr,
    Custode.MCP.RepoTools.PrChecks,
    Custode.MCP.RepoTools.PrDiff,
    Custode.MCP.DisownTools.DisownPr,
    Custode.MCP.DisownTools.ReclaimPr,
    Custode.MCP.DisownTools.ListDisowned,
    Custode.MCP.AskTools.AskOperator,
    Custode.MCP.AskTools.ListAsks,
    Custode.MCP.AskTools.AnswerAsk,
    Custode.MCP.AskTools.DismissAsk,
    Custode.MCP.PeerTools.Send,
    Custode.MCP.PeerTools.Reply,
    Custode.MCP.PeerTools.List,
    Custode.MCP.PeerTools.Read,
    Custode.MCP.PeerTools.Ack,
    Custode.MCP.ReadTools.Attention,
    Custode.MCP.ReadTools.Inbox,
    Custode.MCP.ReadTools.Suggestions,
    Custode.MCP.ReadTools.SuggestionOutcomes,
    Custode.MCP.ReadTools.Advisors,
    Custode.MCP.ReadTools.Metrics,
    Custode.MCP.ReadTools.Digest,
    Custode.MCP.ReadTools.Roles,
    Custode.MCP.ReadTools.Policies,
    Custode.MCP.ReadTools.Workflows,
    Custode.MCP.ReadTools.ExecutingTurns,
    Custode.MCP.ProjectProgressTools.Read,
    Custode.MCP.CurrentRunTools.Read,
    Custode.MCP.IntegrationTools.List,
    Custode.MCP.IntegrationTools.UpdateAccess,
    Custode.MCP.RouteTools.Preview,
    Custode.MCP.BootstrapTools.OperatorBootstrap,
    Custode.MCP.OperatorTools.Beat,
    Custode.MCP.OperatorTools.DropNote,
    Custode.MCP.OperatorTools.ListGates,
    Custode.MCP.OperatorTools.FeedTail,
    Custode.MCP.OperatorTools.ListOperatorMessages,
    Custode.MCP.OperatorTools.PauseAgent,
    Custode.MCP.OperatorTools.SetPresence,
    Custode.MCP.OperatorTools.ResumeAgent,
    Custode.MCP.OperatorTools.SpendToday,
    Custode.MCP.OwnedCheckoutTools.Provision,
    Custode.MCP.OwnedCheckoutTools.Refresh,
    Custode.MCP.NotebookTools.JournalAppend,
    Custode.MCP.NotebookTools.JournalRead,
    Custode.MCP.NotebookTools.CompactJournal,
    Custode.MCP.NotebookTools.SetPanel,
    Custode.MCP.NotebookTools.TodoAdd,
    Custode.MCP.NotebookTools.SetNextBeat,
    Custode.MCP.NotebookTools.TodoList,
    Custode.MCP.NotebookTools.TodoComplete,
    Custode.MCP.NotebookTools.InboxList,
    Custode.MCP.NotebookTools.InboxMarkFiled,
    Custode.MCP.MemoryTools.Remember,
    Custode.MCP.MemoryTools.Recall,
    Custode.MCP.MemoryTools.Forget
  ]
  def tools, do: @tools
  def server_info, do: %{"name" => "custode", "version" => "0.3.0"}
  def server_capabilities, do: %{"tools" => %{}, "resources" => %{}}
end

defmodule Custode.MCP.MemoryServer do
  @moduledoc "Static native Snodo tool catalog for the memory endpoint."
  @tools [
    Custode.MCP.IntegrationTools.List,
    Custode.MCP.NotebookTools.JournalRead,
    Custode.MCP.MemoryTools.Remember,
    Custode.MCP.MemoryTools.Recall,
    Custode.MCP.MemoryTools.Forget
  ]
  def tools, do: @tools
  def server_info, do: %{"name" => "memory", "version" => "0.3.0"}
  def server_capabilities, do: %{"tools" => %{}}
end
